[package]
name = "profiler-flame-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flame = { version = "0.2.2", optional = true }

[features]
default = []
flame_it = ["flame"]
